In [256]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sb
pd.set_option("max.columns", 100)
pd.set_option("max.colwidth", 100)

In [257]:
df = pd.read_csv("loan_training_data.csv")

In [258]:
data_dict = pd.read_csv("the_data_dictionary.csv")
data_dict

,dtypes,name,description
0,float64,loan_amnt,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit ..."
1,object,term,The number of payments on the loan. Values are in months and can be either 36 or 60.
2,float64,installment,The monthly payment owed by the borrower if the loan originates.
3,object,grade,LC assigned loan grade
4,object,emp_length,Employment length in years. Possible values are between 0 and 10 where 0 means less than one yea...
5,object,home_ownership,The home ownership status provided by the borrower during registration or obtained from the cred...
6,float64,annual_inc,The self-reported annual income provided by the borrower during registration.
7,object,verification_status,"Indicates if income was verified by LC, not verified, or if the income source was verified"
8,object,loan_status,Current status of the loan
9,object,purpose,A category provided by the borrower for the loan request.
10,float64,dti,A ratio calculated using the borrower’s total monthly debt payments on the total debt obligation...
11,float64,delinq_2yrs,The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the ...
12,float64,open_acc,The number of open credit lines in the borrower's credit file.
13,float64,revol_bal,Total credit revolving balance
14,float64,total_acc,The total number of credit lines currently in the borrower's credit file
15,float64,tot_coll_amt,Total collection amounts ever owed
16,float64,tot_cur_bal,Total current balance of all accounts
17,float64,total_rev_hi_lim,Total revolving high credit/credit limit
18,float64,avg_cur_bal,Average current balance of all accounts
19,float64,bc_util,Ratio of total current balance to high credit/credit limit for all bankcard accounts.
20,float64,mort_acc,Number of mortgage accounts.
21,float64,num_accts_ever_120_pd,Number of accounts ever 120 or more days past due
22,float64,num_actv_bc_tl,Number of currently active bankcard accounts
23,float64,num_actv_rev_tl,Number of currently active revolving trades
24,float64,num_bc_sats,Number of satisfactory bankcard accounts
25,float64,num_bc_tl,Number of bankcard accounts
26,float64,num_rev_tl_bal_gt_0,Number of revolving trades with balance >0
27,float64,num_tl_90g_dpd_24m,Number of accounts 90 or more days past due in last 24 months
28,float64,num_tl_op_past_12m,Number of accounts opened in past 12 months
29,float64,total_bal_ex_mort,Total credit balance excluding mortgage
30,float64,total_bc_limit,Total bankcard high credit/credit limit
31,float64,total_il_high_credit_limit,Total installment high credit/credit limit
32,floa64,fico_average,The average of the fico high and low range scores

In [259]:
df.head()

,loan_amnt,term,installment,grade,emp_length,home_ownership,annual_inc,verification_status,loan_status,purpose,dti,delinq_2yrs,open_acc,revol_bal,total_acc,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,avg_cur_bal,bc_util,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_rev_tl_bal_gt_0,num_tl_90g_dpd_24m,num_tl_op_past_12m,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,fico_average
0,15000.0,36 months,485.14,B,9 years,MORTGAGE,125000.0,Not Verified,1,debt_consolidation,17.22,0.0,11.0,37651.0,24.0,0.0,87483.0,58300.0,7953.0,53.6,2.0,0.0,2.0,7.0,2.0,8.0,7.0,0.0,1.0,87483.0,8500.0,45764.0,687.0
1,12250.0,60 months,295.37,C,7 years,RENT,35000.0,Source Verified,0,credit_card,19.51,0.0,9.0,12681.0,19.0,0.0,13938.0,19345.0,1742.0,69.1,0.0,0.0,5.0,5.0,7.0,16.0,5.0,0.0,1.0,13938.0,18345.0,14793.0,722.0
2,17000.0,36 months,556.48,B,10+ years,MORTGAGE,67000.0,Source Verified,1,debt_consolidation,21.26,0.0,14.0,27320.0,33.0,0.0,43035.0,43500.0,3074.0,66.2,1.0,0.0,4.0,6.0,6.0,12.0,6.0,0.0,0.0,43035.0,31800.0,27657.0,747.0
3,8250.0,36 months,263.01,B,9 years,OWN,29000.0,Not Verified,1,debt_consolidation,24.34,0.0,14.0,8253.0,22.0,0.0,46863.0,13600.0,3347.0,71.8,0.0,0.0,4.0,5.0,4.0,4.0,5.0,0.0,0.0,46863.0,11400.0,40279.0,702.0
4,7125.0,36 months,256.06,D,9 years,RENT,87000.0,Source Verified,0,house,13.92,2.0,12.0,2426.0,19.0,1215.0,22318.0,5400.0,1860.0,47.2,0.0,0.0,5.0,7.0,7.0,8.0,8.0,0.0,2.0,22318.0,4700.0,26334.0,677.0

In [260]:
X = df.drop("loan_status", axis=1)
y = df.loan_status

In [261]:
term_dummies = pd.get_dummies(X.term, prefix="term:")
grade_dummies = pd.get_dummies(X.grade, prefix="grade:")
home_dummies = pd.get_dummies(X.home_ownership, prefix="home:")
verified_dummies = pd.get_dummies(X.verification_status, prefix="verify:")
purpose_dummies = pd.get_dummies(X.purpose, prefix="purpose")
dummies = pd.concat([grade_dummies,home_dummies,purpose_dummies, term_dummies, verified_dummies], axis=1)
X.drop(["term", "grade", "home_ownership", "verification_status", "purpose"], axis=1, inplace=True)
X = pd.concat([X,dummies], axis=1)
X["emp_length"] = X.emp_length.str.replace(" years", "").str.replace(" year", "").str.replace("< 1", "0").str.replace("+", "").str.replace("n/a", "0")
X["emp_length"] = X.emp_length.astype(float)

In [262]:
X.head()

,loan_amnt,installment,emp_length,annual_inc,dti,delinq_2yrs,open_acc,revol_bal,total_acc,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,avg_cur_bal,bc_util,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_rev_tl_bal_gt_0,num_tl_90g_dpd_24m,num_tl_op_past_12m,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,fico_average,grade:_A,grade:_B,grade:_C,grade:_D,grade:_E,grade:_F,grade:_G,home:_MORTGAGE,home:_NONE,home:_OTHER,home:_OWN,home:_RENT,purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,term:_ 36 months,term:_ 60 months,verify:_Not Verified,verify:_Source Verified,verify:_Verified
0,15000.0,485.14,9.0,125000.0,17.22,0.0,11.0,37651.0,24.0,0.0,87483.0,58300.0,7953.0,53.6,2.0,0.0,2.0,7.0,2.0,8.0,7.0,0.0,1.0,87483.0,8500.0,45764.0,687.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1,12250.0,295.37,7.0,35000.0,19.51,0.0,9.0,12681.0,19.0,0.0,13938.0,19345.0,1742.0,69.1,0.0,0.0,5.0,5.0,7.0,16.0,5.0,0.0,1.0,13938.0,18345.0,14793.0,722.0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
2,17000.0,556.48,10.0,67000.0,21.26,0.0,14.0,27320.0,33.0,0.0,43035.0,43500.0,3074.0,66.2,1.0,0.0,4.0,6.0,6.0,12.0,6.0,0.0,0.0,43035.0,31800.0,27657.0,747.0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
3,8250.0,263.01,9.0,29000.0,24.34,0.0,14.0,8253.0,22.0,0.0,46863.0,13600.0,3347.0,71.8,0.0,0.0,4.0,5.0,4.0,4.0,5.0,0.0,0.0,46863.0,11400.0,40279.0,702.0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
4,7125.0,256.06,9.0,87000.0,13.92,2.0,12.0,2426.0,19.0,1215.0,22318.0,5400.0,1860.0,47.2,0.0,0.0,5.0,7.0,7.0,8.0,8.0,0.0,2.0,22318.0,4700.0,26334.0,677.0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0

In [263]:
#WITH TEST DATA

In [264]:
dft = pd.read_csv("loan_testing_data.csv").sample(frac=.2, random_state=1234)
dft.shape

(10000, 33)

In [265]:
Xt = dft.drop("loan_status", axis=1)
yt = dft.loan_status

Xt.shape

(10000, 32)

In [266]:
term_dummies_t = pd.get_dummies(Xt.term, prefix="term:")
grade_dummies_t = pd.get_dummies(Xt.grade, prefix="grade:")
home_dummies_t = pd.get_dummies(Xt.home_ownership, prefix="home:")
verified_dummies_t = pd.get_dummies(Xt.verification_status, prefix="verify:")
purpose_dummies_t = pd.get_dummies(Xt.purpose, prefix="purpose")
dummies_t = pd.concat([grade_dummies_t,home_dummies_t,purpose_dummies_t, term_dummies_t, verified_dummies_t], axis=1)
Xt.drop(["term", "grade", "home_ownership", "verification_status", "purpose"], axis=1, inplace=True)
Xt = pd.concat([Xt,dummies_t], axis=1)
Xt["emp_length"] = Xt.emp_length.str.replace(" years", "").str.replace(" year", "").str.replace("< 1", "0").str.replace("+", "").str.replace("n/a", "0")
Xt["emp_length"] = Xt.emp_length.astype(float)

In [267]:
for i in X.columns:
    if i not in Xt.columns:
        print i
for i in X.columns:
    if i not in Xt.columns:
        X.drop(i, axis=1, inplace=True)

home:_NONE

In [268]:
import numpy as np
np.size(X.columns)

56

In [269]:
np.size(Xt.columns)

56

In [270]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
Xs = scale.fit_transform(X)
Xts = scale.transform(Xt)

In [271]:
from sklearn.metrics import confusion_matrix
#Profit calculator
def profit_calculator(y_test, y_pred):
    cm = confusion_matrix(y_test, y_pred)
    tp = cm[1,1]
    fp = cm[0,1]
    return 100*tp - 1000*fp

In [272]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Xs, y, test_size=0.30, random_state=101)
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier(random_state=42)
model.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=42,
              subsample=1.0, verbose=0, warm_start=False)

In [273]:
y_prob_pred = model.predict_proba(X_test)
threshold_adjusted_preds = np.where(y_prob_pred>=0.93, 1, 0)
predictions = threshold_adjusted_preds[:,1]
profit_calculator(y_test, predictions)

120900

In [274]:
#TEST DATA

In [275]:
yt_prob_pred = model.predict_proba(Xts)
threshold_adjusted_test_preds = np.where(yt_prob_pred>=0.9, 1, 0)
test_predictions1 = threshold_adjusted_test_preds[:,1]
profit_calculator(yt, test_predictions1)

77400